Repository MirageNet/Mirage, pull requests merged in 2021-04, with the labels that each got.

#767 fix: using add late event for authority and combining start and stop events
  Assets/Mirage/Runtime/Events/BoolAddLateEvent.cs
  Assets/Mirage/Runtime/Events/BoolAddLateEvent.cs.meta
  Assets/Mirage/Runtime/NetworkIdentity.cs
  Assets/Tests/Editor/NetworkIdentityCallbackTests.cs
  doc/Articles/Guides/GameObjects/Lifecycle.md
  doc/Articles/Guides/MirrorMigration.md
Labels: has conflicts

#768 fix: using AddLateEvent to stop race condition for client events
  Assets/Mirage/Runtime/Events/NetworkPlayerAddLateEvent.cs
  Assets/Mirage/Runtime/Events/NetworkPlayerAddLateEvent.cs.meta
  Assets/Mirage/Runtime/INetworkClient.cs
  Assets/Mirage/Runtime/INetworkServer.cs
  Assets/Mirage/Runtime/NetworkClient.cs
  Assets/Mirage/Runtime/NetworkServer.cs
Labels: has conflicts

#774 refactor: remove client from replacecharacter
  Assets/Mirage/Runtime/IServerObjectManager.cs
  Assets/Mirage/Runtime/ServerObjectManager.cs
  Assets/Tests/Runtime/ClientServer/ServerObjectManagerTests.cs
  Assets/Tests/Runtime/Host/ClientObjectManagerTest.cs
Labels: ready to merge

#777 refactor: remove duplicated ref to player can be accessed from client
  Assets/Mirage/Runtime/ClientObjectManager.cs
  Assets/Mirage/Runtime/IClientObjectManager.cs
  Assets/Mirage/Runtime/NetworkIdentity.cs
  Assets/Mirage/Samples~/Tanks/Scripts/TankGameManager.cs
  doc/Articles/Guides/MirrorMigration.md
Labels: ready for review

#785 refactor: remove internal method as replace is no longer virtual
  Assets/Mirage/Runtime/ServerObjectManager.cs
  Assets/Tests/Runtime/ClientServer/ServerObjectManagerTests.cs
Labels: ready for review

#787 refactor: identity assignment standardized
  Assets/Mirage/Runtime/ClientObjectManager.cs
  Assets/Mirage/Runtime/NetworkIdentity.cs
  Assets/Mirage/Runtime/ServerObjectManager.cs
Labels: ready for review

#788 fix: server offline exception does not need a specific object
  Assets/Mirage/Runtime/ServerObjectManager.cs
  Assets/Tests/Runtime/ClientServer/ServerObjectManagerTests.cs
Labels: ready for review

#793 refactor: renaming network server disconnect to stop
  Assets/Mirage/Runtime/INetworkServer.cs
  Assets/Mirage/Runtime/NetworkServer.cs
  Assets/Tests/Performance/Runtime/MultipleClients/MultipleClients.cs
  Assets/Tests/Runtime/ClientServer/ClientServerSetup.cs
  Assets/Tests/Runtime/ClientServer/NetworkServerTests.cs
  Assets/Tests/Runtime/ClientServer/ServerObjectManagerTests.cs
  Assets/Tests/Runtime/Host/HostComponentTests.cs
  Assets/Tests/Runtime/Host/NetworkManagerTest.cs
  Assets/Tests/Runtime/Host/ServerObjectManagerTest.cs
  Assets/Tests/Runtime/NetworkIdentityCallbackTests.cs
Labels: ready for review

#792 refactor: rewrite assembler for weaver tests
  Assets/Tests/Weaver/Assembler.cs
  Assets/Tests/Weaver/SyncVarTests.cs
  Assets/Tests/Weaver/Tests.cs
  Assets/Tests/Weaver/WeaverTestLocator.cs
  Assets/Tests/Weaver/WeaverTestLocator.cs.meta
Labels: ready for review
