Repository MirageNet/Mirage, pull requests merged in 2021-02, with the labels that each got.

#562 fix: better benchmark
  Assets/Tests/Performance/Runtime/HeadlessBenchmark/Scenes/Scene.unity
  Assets/Tests/Performance/Runtime/HeadlessBenchmark/Scripts/AdjustableLoad.cs
  Assets/Tests/Performance/Runtime/HeadlessBenchmark/Scripts/HeadlessBenchmark.cs
Labels: Work In Progess

#571 feat: open changelog page when user downloaded a new version
  Assets/Mirror/Editor/WelcomeWindow/Resources/WelcomeWindow.uss
  Assets/Mirror/Editor/WelcomeWindow/Resources/WelcomeWindow.uxml
  Assets/Mirror/Editor/WelcomeWindow/WelcomeWindow.cs
Labels: Needs testing, enhancement, good first issue

#573 style: reorder positions of serializable fields in networkmanager components
  Assets/Mirror/Runtime/ClientObjectManager.cs
  Assets/Mirror/Runtime/NetworkClient.cs
  Assets/Mirror/Runtime/NetworkSceneManager.cs
  Assets/Mirror/Runtime/NetworkServer.cs
  Assets/Mirror/Runtime/ServerObjectManager.cs
Labels: enhancement

#597 doc: update discord link in README.md
  README.md
Labels: documentation

#574 feat: rpcs and syncvars now support generic components
  Assets/Mirage/Weaver/Extensions.cs
  Assets/Mirage/Weaver/MethodExtensions.cs
  Assets/Mirage/Weaver/Processors/ClientRpcProcessor.cs
  Assets/Mirage/Weaver/Processors/FieldReferenceComparator.cs
  Assets/Mirage/Weaver/Processors/PropertySiteProcessor.cs
  Assets/Mirage/Weaver/Processors/RpcProcessor.cs
  Assets/Mirage/Weaver/Processors/ServerRpcProcessor.cs
  Assets/Mirage/Weaver/Processors/SyncObjectProcessor.cs
  Assets/Mirage/Weaver/Processors/SyncVarProcessor.cs
  Assets/Mirage/Weaver/TypeExtensions.cs
  Assets/Tests/Runtime/ClientServer/GenericNetworkBehaviorSyncvarTest.cs
  Assets/Tests/Runtime/ClientServer/GenericNetworkBehaviorSyncvarTest.cs.meta
  Assets/Tests/Runtime/ClientServer/GenericNetworkBehaviourDeeperRpcTest.cs
  Assets/Tests/Runtime/ClientServer/GenericNetworkBehaviourDeeperRpcTest.cs.meta
  Assets/Tests/Runtime/ClientServer/GenericNetworkBehaviourRpcTest.cs
  Assets/Tests/Runtime/ClientServer/GenericNetworkBehaviourRpcTest.cs.meta
  Assets/Tests/Runtime/ClientServer/GenericNetworkBehaviourSyncvarDeeperTest.cs
  Assets/Tests/Runtime/ClientServer/GenericNetworkBehaviourSyncvarDeeperTest.cs.meta
  Assets/Tests/Runtime/ClientServer/GenericNetworkBehaviourSyncvarNoMiddleTest.cs
  Assets/Tests/Runtime/ClientServer/GenericNetworkBehaviourSyncvarNoMiddleTest.cs.meta
Labels: Work In Progess

#637 fix: mirage icon missing in welcome window
  Assets/Mirage/Editor/WelcomeWindow/Resources/WelcomeWindow.uxml
Labels: good first issue
